# Generated by Django 4.2 on 2023-04-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaga',
            new_name='Vacancies',
        ),
    ]
