# Generated by Django 4.2 on 2023-04-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_rename_vaga_vacancies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancies',
            new_name='Vacancie',
        ),
    ]
