# Generated by Django 4.2 on 2023-04-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_rename_categories_categorie'),
        ('vagas', '0003_rename_vacancies_vacancie'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancie',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categorie'),
            preserve_default=False,
        ),
    ]
