# Generated by Django 4.2 on 2023-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_vacancie_city_vacancie_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancie',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
