# Generated by Django 4.2 on 2023-04-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_vacancie_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancie',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Vacancies number'),
        ),
    ]
