# Generated by Django 4.2 on 2023-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_alter_vacancie_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancie',
            name='type',
            field=models.CharField(choices=[('INTERSHIP', 'Internship'), ('JOB', 'Job'), ('HOME OFFICE', 'Home office')], default=1, max_length=11, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
