# Generated by Django 4.2 on 2023-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news_img/%Y/%m/%d', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
