# Generated by Django 4.2 on 2023-05-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_rename_vacancie_vacancy'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
