# Generated by Django 4.2 on 2023-04-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_categoria_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
