# Generated by Django 5.0.2 on 2024-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="schooling",
            field=models.CharField(
                choices=[
                    ("HSC", "High school"),
                    ("ASD", "Associates degree"),
                    ("UND", "Undergraduate degree"),
                    ("MSD", "Master's degree"),
                    ("DCT", "Doctorate"),
                ],
                max_length=3,
                verbose_name="Schooling",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("NP", "Natural person"), ("LP", "Legal person")],
                max_length=3,
                verbose_name="User type",
            ),
        ),
    ]
