# Generated by Django 4.2 on 2023-05-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conta',
            new_name='Account',
        ),
    ]
