# Generated by Django 4.2 on 2023-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_conta_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='schooling',
            field=models.CharField(choices=[('TEC', 'Technology'), ('SRV', 'Service'), ('CMC', 'Communication'), ('ACT', 'Accounting'), ('EDC', 'Education'), ('SEC', 'Security')], max_length=3, verbose_name='Schooling'),
        ),
    ]
