# Generated by Django 4.2 on 2023-05-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_about_you_profile_address_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp',
        ),
    ]
