# Generated by Django 4.2 on 2023-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.IntegerField(default=1, verbose_name='WhatsApp'),
            preserve_default=False,
        ),
    ]
