# Generated by Django 4.2 on 2023-05-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_about_you_account_address_account_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('TEC', 'Technology'), ('SRV', 'Service'), ('CMC', 'Communication'), ('ACT', 'Accounting'), ('EDC', 'Education'), ('SEC', 'Security')], max_length=3, verbose_name='User type'),
        ),
    ]
