# Generated by Django 4.2 on 2023-05-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_account_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=1, max_length=255, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='neighborhood',
            field=models.CharField(max_length=255, verbose_name='Neighborhood'),
        ),
    ]
