# Generated by Django 4.2 on 2023-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveBigIntegerField(verbose_name='Phone number'),
        ),
    ]
