# Generated by Django 4.2 on 2023-05-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_account_username_alter_account_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Profile',
        ),
    ]
