# Generated by Django 4.2 on 2023-05-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_about_you_profile_address_profile_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
