# Generated by Django 4.2 on 2023-07-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='occupation_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='occupation.occupation'),
            preserve_default=False,
        ),
    ]
