# Generated by Django 4.2 on 2023-06-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact_number',
            field=models.PositiveBigIntegerField(default=98992078248, verbose_name='WhatsApp'),
            preserve_default=False,
        ),
    ]
