# Generated by Django 4.2 on 2023-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancie_about_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancie',
            name='requirements',
            field=models.TextField(default=1, verbose_name='Requirements'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancie',
            name='about_company',
            field=models.TextField(verbose_name='About the company'),
        ),
    ]
