# Generated by Django 4.2 on 2023-06-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact_whatsapp',
            field=models.PositiveBigIntegerField(default=98991078248, verbose_name='WhatsApp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_number',
            field=models.PositiveBigIntegerField(verbose_name='Phone number'),
        ),
    ]
