# Generated by Django 4.2 on 2023-07-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_occupation_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='occupation_area',
        ),
    ]
