# Generated by Django 5.0.2 on 2024-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_alter_vacancy_occupation_area_alter_vacancy_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="visibility",
            field=models.BooleanField(default=False, verbose_name="Visible"),
        ),
    ]
