# Generated by Django 4.2 on 2023-06-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_contact_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
