# Generated by Django 4.2 on 2023-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='visibility',
            field=models.BooleanField(default=False, editable=False, verbose_name='Visible'),
        ),
    ]
