# Generated by Django 4.2 on 2023-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancie_requirements_alter_vacancie_about_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancie',
            name='activities',
            field=models.TextField(default=1, verbose_name='Activities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancie',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='vacancie',
            name='salary',
            field=models.TextField(default=1, verbose_name='Salary'),
            preserve_default=False,
        ),
    ]
