# Generated by Django 4.2 on 2023-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_vacancy_occupation_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='occupation_area',
            field=models.CharField(choices=[('TEC', 'Technology'), ('SRV', 'Service'), ('CMC', 'Communication'), ('ACT', 'Accounting'), ('EDC', 'Education'), ('SEC', 'Security')], max_length=3, verbose_name='Occupation area'),
        ),
    ]
