# Generated by Django 4.2 on 2023-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_vacancie_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancie',
            name='schedule',
            field=models.CharField(max_length=300, verbose_name='Schedule'),
        ),
    ]
