# Generated by Django 4.2 on 2023-07-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancy_occupation_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Visible'),
            preserve_default=False,
        ),
    ]
