# Generated by Django 4.2 on 2023-04-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_vacancie_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancie',
            name='occupation_area',
            field=models.CharField(default=1, max_length=255, verbose_name='Occupation area'),
            preserve_default=False,
        ),
    ]
