# Generated by Django 4.2 on 2023-07-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_vacancy_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='visibility',
        ),
    ]
