# Generated by Django 4.2 on 2023-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_vacancy_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
