# Generated by Django 4.2 on 2023-04-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_alter_vacancie_occupation_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancie',
            name='kind',
        ),
    ]
