# Generated by Django 4.2 on 2023-05-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('vacancies', '0011_remove_vacancie_kind'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancie',
            new_name='Vacancy',
        ),
    ]
