# Generated by Django 4.2 on 2023-05-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_rename_vacancie_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='categorie',
            new_name='category',
        ),
    ]
