# Generated by Django 4.2 on 2023-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_remove_vacancy_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
