# Generated by Django 4.2 on 2023-05-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_conta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conta',
        ),
    ]
