# Generated by Django 4.2 on 2023-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_alter_vacancy_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
