# Generated by Django 4.2 on 2023-07-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_state_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
    ]
