# Generated by Django 5.0.2 on 2024-03-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("state", "0004_state_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=255, verbose_name="State"),
        ),
    ]
